# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://sadhu89.github.io/
baseurl: ""
title: Carlos Rojas
author: Carlos Rojas
description: Personal blog and resume
avatar: profile.jpeg
email: carlos.sadhu@gmail.com
github: sadhu89 # username
twitter: CarlosSadhu
linkedin: crojasn
stackoverflow: users/4808245/carlos-sadhu-rojas-Ñiquen
disqus: carlossadhu
google_analytics: UA-76952875-1


# needed for travis-ci build
exclude: [vendor]
