# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://lmarulanda.github.io/
baseurl: ""
title: Laura Marulanda
author: Laura Marulanda
description: Personal blog and resume
avatar: profile.jpeg
email: lauris037.lm@gmail.com
github: lmarulanda # username
twitter: 
linkedin: lmarulanda
stackoverflow: 
disqus: 
google_analytics: 


# needed for travis-ci build
exclude: [vendor]
